#ifndef PROCESS_H
#define PROCESS_H

enum class Process
{
    MAIN_MENU,
    READ_MENU,
    SEND_MENU,
    SETTINGS,
    BATTERY_INFO,
    COPY_REMOTE_ENTER_NAME,
    COPY_REMOTE_CONTROLS,
    COPY_MAIN_CONTROLS,
    COPY_NUMBERS,
    COPY_NAVIGATION,
    COPY_MISC,
    LOAD_REMOTE,
    SAVE_CONTROLS,
    LOAD_REMOTE_INTO_MEMORY,
    SEND_REMOTE_CONTROLS,
    SEND_MAIN_CONTROLS,
    SEND_NUMBERS,
    SEND_NAVIGATION,
    SEND_MISC,
    SEND_COMMAND
};

#endif